CREATE TABLE IF NOT EXISTS `audit_logs` (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `timestamp` datetime NOT NULL,
  `event_type` varchar(50) NOT NULL,
  `user_id` bigint UNSIGNED NULL,
  `ip_address` varchar(45) NOT NULL,
  `user_agent` varchar(255) NULL,
  `endpoint` varchar(255) NOT NULL,
  `http_method` varchar(10) NOT NULL,
  `request_id` varchar(36) NOT NULL,
  `status` enum('SUCCESS','FAIL') NOT NULL,
  `severity` enum('INFO','WARNING','CRITICAL') NOT NULL DEFAULT 'INFO',
  `metadata` json NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_timestamp` (`timestamp`),
  KEY `idx_event_type` (`event_type`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_ip_address` (`ip_address`),
  KEY `idx_request_id` (`request_id`),
  KEY `idx_severity` (`severity`),
  KEY `idx_status` (`status`),
  KEY `idx_endpoint` (`endpoint`),
  KEY `idx_event_timestamp` (`event_type`, `timestamp`),
  KEY `idx_user_timestamp` (`user_id`, `timestamp`),
  CONSTRAINT `audit_logs_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
